# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from openerp.osv import fields, osv

class usuarios_venezuela(osv.osv):
    """Usuarios venezuela"""
    _name = 'res.users'
    _inherit = 'res.users'
    
    
    def limpiar_campos(self,cr,uid,ids,nombre):
        res={}
        if nombre=='estado':
            res={
            'municipio_id':'',
            'parroquia_id':'',
            #~ 'sector_id':'',
                }
        if nombre=='municipio':
            res={
            'parroquia_id':'',
            #~ 'sector_id':'',
                }
        return {
         'value':res
            }
    
    _columns = {
        'cedula': fields.char('Cedula de Identidad',
                     size=15,
                     required=True,
                     help='Cedula de Identidad del Usuario'
                     ),
        'telefono': fields.char('Telefono',
                    size=20,
                    help='Teléfono de Contacto del Usuario'
                    ),
        'estado_id': fields.many2one('res.estados',
                    'Estado',
                    required=True,
                    help='Estado donde vive el usuario'),
        'municipio_id': fields.many2one('res.municipios',
                    'Municipio',
                    required=True,
                    help='Municipio donde vive el usuario'),
        'parroquia_id': fields.many2one('res.parroquias',
                    'Parroquia',
                    required=True,
                    help='Parroquia donde vive el usuario'),
        'sector': fields.char('Sector',
                    size=80,
                    help='Sector donde vive el usuario'
                    ),
        'calle_av': fields.char('Calle/Avenida',
                    size=80,
                    help='Calle/Avenida donde vive el usuario'
                    ),
        'casa_edif': fields.char('Casa/Edificio',
                    size=80,
                    help='Casa/Edificio donde vive el usuario'
                    ),
        'piso_apart': fields.char('Piso y Apartemento',
                    size=20,
                    help='Piso y Apartemento donde vive el usuario'
                    ),
    }


